/* Main.c file generated by Monsij
 *
 * Created:   Sat Apr 14 2018
 * Processor: 80C31
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
int i;
int j;
int k;
char nums[10]={0x03F,0x06,0x05b,0x4f,0x66,0x6d,0x7D,0x7,0xff,0x6f};
void main(void)
 { 
   // Write your code here
   while (1)
   {
      for(i=0; i<10; i++){
	 P1=nums[i];
	 
	 for(j=0; j<20000; j++); //Delay
	    for(k=0; k<20000; k++);
	    }
   }
}
      
      
 }